version: "3.7"

services:
  nginx:
    image: nginx:1.19.5

    ports:
      - 80:80

    networks:
      - gis_4_1_network

    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - gis_4_1_static:/data/static
      - gis_4_1_media:/data/media

  django:
    image: gis_4_1_django:1.0.3

    networks:
      - gis_4_1_network

    volumes:
      - gis_4_1_static:/home/gis4-1/staticfiles/
      - gis_4_1_media:/home/gis4-1/media/

    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5

    networks:
      - gis_4_1_network

    volumes:
      - gis_4_1_mariadb:/var/lib/mysql

    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD

    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1234


networks:
  gis_4_1_network:

volumes:
  gis_4_1_static:
  gis_4_1_media:
  gis_4_1_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true